---
title: New issue of the Norwegian Journal of Nutrition
author: Vegard
date: 2019-09-17
slug: new-issue-of-the-norwegian-journal-of-nutrition
categories:
  - updates
tags:
subtitle: ''
summary: ''
authors: []
lastmod: '2019-09-17T22:31:22+02:00'
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
A new issue of [the Norwegian Journal of Nutrition](http://www.ntfe.no/) was published today. All the articles in this issue are in Norwegian.

I make two contributions to this issue. First, my former bachelor student Åslaug O. Matre published a paper based on her bachelor thesis: [Cobalamin supplements without cobalamin deficiency?](http://www.ntfe.no/i/2019/3/ntfe-2019-03-21). In her thesis, she conducted a literature study investigating whether individuals with subclinical, but not overt, cobalamin deficiency would benefit from cobalamin supplements. The main findings were that supplementation did not appear beneficial with regard to cognitive function in adults with biochemical signs of subclinical cobalamin deficiancy. In infants with subclinical deficiency, supplementation appeared to improve motoric function. Further, supplementation of pregnant women with marginal cobalamin status did show a small benefit regarding language development of the child.

My second contribution to this issue was a report from [the 12^th^ international conference on one-carbon metabolism, B-vitamins and homocysteine](http://www.ntfe.no/i/2019/3/ntfe-2019-03-1390), arranged in Spain this august. 

In this issue you can also, among other things, read an interesting article by [Martin Norum](https://www.martinnorum.no/) about [periodization of carbohydrate intake related to endurance performance](http://www.ntfe.no/i/2019/3/ntfe-2019-03-707).