---
title: Articles and chronicles
author: Vegard
date: 2019-09-04
slug: articles
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: 2019-09-04
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
---
This is a list of articles and chronicles I've written together with various colleagues.

## 2021
- [Nei, det er ikke lettbrus som gjør deg tjukk](https://forskersonen.no/kronikk-mat-og-helse-meninger/nei-det-er-ikke-lettbrus-som-gjor-deg-tjukk/1864932), **Forskersonen**, with Thomas Olsen and Martin Norum.

## 2019
- [Norske kostråd anbefaler ikke «vestlig kosthold»](https://www.dagensmedisin.no/artikler/2019/08/23/norske-kostrad-anbefaler-ikke-vestlig-kosthold/) - **Dagens Medisin**, with Hanna Dale. 

## 2018
- [Fagfolk ut mot myndighetene: Sukkerfri brus bør ikke rammes av sukkeravgiften](https://www.aftenposten.no/meninger/debatt/i/BJEz19/Fagfolk-ut-mot-myndighetene-Sukkerfri-brus-bor-ikke-rammes-av-sukkeravgiften--Olsen_-Dahl-og-Lysne) - **Aftenposten**, with Helene Dahl and Thomas Olsen
- [Ikke skrot BMI!](https://www.nrk.no/ytring/ikke-skrot-bmi_-1.14259175) - **NRK Ytring**, with Thomas Olsen, Bente Øvrebø and Erik Arnesen

## 2017
- [Ja, det er et poeng å bytte til lettbrus!](https://www.dagbladet.no/kultur/ja-det-er-et-poeng-a-bytte-til-lettbrus/69352581) - **Dagbladet**, with Thomas Olsen, Jacob Juel Christensen and Erik Arnesen

## 2016
- [Kostråd er også et spørsmål om pasientsikkerhet](https://www.bt.no/btmeninger/kronikk/i/gL4mA/kostraad-er-ogsaa-et-spoersmaal-om-pasientsikkerhet) - **Bergens Tidende**, with Jacob Juel Christensen
- [Vi undergraver ikke sykepleiernes rolle](https://www.bt.no/btmeninger/debatt/i/Bywne/Vi-undergraver-ikke-sykepleiernes-rolle) - **Bergens Tidende**, with Jacob Juel Christensen

## 2015
- [Skremselspropaganda mot kostholdsråd](https://www.dagbladet.no/2015/01/09/kultur/meninger/kronikk/debatt/kosthold/37079284/) - **Dagbladet**, with Thomas Olsen and Erik Arnesen
- [Slankeråd: Forvirring til frokost](https://www.aftenposten.no/meninger/debatt/i/ngVoJ/Slankerad-Forvirring-til-frokost) - **Aftenposten**, with Brita Haugum and Aslaug Drotningsvik
- [Kostholdsdebatten: Poenget som forsvant](https://www.aftenposten.no/meninger/debatt/i/zLVz5/Kostholdsdebatten-Poenget-som-forsvant) - **Aftenposten**, with Brita Haugum and Aslaug Drotningsvik

## 2014
- [Ernæringseksperter, melk og kildekritikk](https://www.nrk.no/ytring/eksperter_-melk-og-kildekritikk-1.11799652) - **NRK Ytring**,  with Thomas Olsen and Erik Arnesen
