---
title: Presentations
author: Vegard
date: '2019-10-02'
slug: presentations
lastmod: '2020-05-27'
draft: no
---

This is a list of my presentations and posters at conferences and meetings. 

# 2020

## Sunn Idrett konferansen 2020, Oslo, Norway

This talk on critical thinking, with a focus on how we are being misled by our own experiences and observations, was given at the annual conference organized by [Sunn Idrett](https://sunnidrett.no/), a focus area of The Norwegian Olympic and Paralympic Committee and Confederation of Sports ([Norges idrettsforbund](https://www.idrettsforbundet.no/)). In the presentation I touch upon topics like anecdotal evidence, regression towards the mean, survivorship bias, and how to deal with all the conflicting information on the topics of diet and exercise. 

- Slides: [Kildekritikk og kritisk tenkning - begynn med deg selv](/contributions/presentations/sunnidrett_2020.pdf)
- [Video](https://sunnidrett.no/se-opptakene-fra-sunn-idrett-konferansen-2020/)

## Mohn Nutrition Research Laboratory seminar, Solstrand, Bergen, Norway

This was the first seminar organized by the Mohn Nutrition Research Laboratory. I presented a workshop on the topics of P-values and statistical significance. The main goal was to reflect on our current approach, and discuss how we may improve.

- Workshop: [P-values and statistical significance](/contributions/presentations/significance_workshop_2020.pdf)

# 2019

## [FENS](http://www.fens2019.org/), Dublin, Ireland

- Poster: [Dietary composition is associated with one-carbon metabolites and B-vitamin status in patients with stable angina - a cross-sectional study](/contributions/posters/FENS2019.pdf)

## Phd defence

- Trial lecture: [Nutritional challenges related to  B-vitamins](/contributions/presentations/PhD_triallecture_04102019.pdf)
- Defence lecture: [Biomarkers of One-carbon metabolism and B-vitamin status](/contributions/presentations/PhD_defence_04102019.pdf)


## 12^th^ International Conference on One Carbon Metabolism, B vitamins and Homocysteine, Tarragona, Spain

- Poster: [Dietary composition is associated with one-carbon metabolites and B-vitamin status in patients with stable angina](/contributions/posters/Homocysteine2019.pdf)

# 2018

## FASEB meeting on Folic Acid, Vitamin B12 and One-carbon metabolism, Halifax, Canada

- Poster: [The Effect of Dietary Fat Intake on Plasma Concetnration of One-Carbon Metabolites and Markers of B-vitamin Status](/contributions/posters/FASEB2018.pdf)

# 2017

## 11^th^ International Conference on Homocysteine  & One-carbon metabolism, Aarhus, Denmark

- Poster: [Exploring dimethylglycine, Methylmalonic Acid and Nicotinamide ad Predictors of Acute Myocardial Infarction and Mortality](/contributions/posters/Homocysteine2017.pdf)

# 2016

## FASEB meeting on Folic Acid, Vitamin B12 and One-carbon metabolism, Colorado, USA

- Presentation: [PPAR&alpha; activation influences plasma one-carbon metabolites and B-vitamin status in rats](/contributions/presentations/FASEB2016.pdf)
- Poster: [PPAR&alpha; activation influences plasma one-carbon metabolites and B-vitamin status in rats](/contributions/posters/FASEB2016.pdf)