---
title: Publications
author: 
date: 2019-09-04
lastmod: 2019-12-06
summary: ''
slug: publications
categories: 
tags: []
---
[Go to other publications](#Other)

## Journal publications {#Journal}

1. `2019` **Lysne V**, Bjørndal B, Grinna ML, Midttun Ø, Ueland PM, Berge RK, Dierkes J, Nygård O and Strand E. **Short-term treatment with a peroxisome proliferator-activated receptor α agonist influences plasma one-carbon metabolites and B-vitamin status in rats.** PLoS One. <br> [PubMed: 31805132](https://www.ncbi.nlm.nih.gov/pubmed/31805132), [Full text](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0226069)

1. `2019` Parys AV, **Lysne V**, Svingen GFT, Ueland PM, Dhar I, Øyen J, Dierkes J and Nygård O. **Dietary choline is related to increased risk of acute myocardial infarction in patients with stable angina pectoris**. Biochimie <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/31707100), [Full text](https://reader.elsevier.com/reader/sd/pii/S0300908419303165?token=66DDCC5B71255E5EDB54BB663B46E53A86BA06853189C9C28E7855F1C42966D9B831C5365F79C2955AF8D9365D93DBEE)

1. `2019` Olsen T, Vinknes KJ, Blomhoff R, **Lysne V**, Midttun Ø, Dhar I, Ueland PM, Svingen GFT, Pedersen ER, Drevon CA, Refsum H, Nygård O. <br> **Creatinine, total cysteine and uric acid are associated with serum retinol in patients with cardiovascular disease**. Eur J Nutr. <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/31502058), [Full text](https://link.springer.com/article/10.1007/s00394-019-02086-2)

1. `2019` Strand E, **Lysne V**, Grinna ML, Bohov P, Svardal A, Nygård O, Berge RK, Bjørndal B. <br> **Short-Term Activation of Peroxisome Proliferator-Activated Receptors &alpha; and &gamma; Induces Tissue-Specific Effects on Lipid Metabolism and Fatty Acid Composition in Male Wistar Rats.** PPAR res. <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/31308847), [Full text](https://www.hindawi.com/journals/ppar/2019/8047627/)

1. `2019` Ulven SM, Christensen JJ, Nygård O, Svardal A, Leder L, Ottestad I, **Lysne V**, Laupsa-Borge J, Ueland PM, Midttun Ø, Meyer K, McCann A, Andersen LF, Holven KB. <br> **Using metabolic profiling and gene expression analyses to explore molecular effects of replacing saturated fat with polyunsaturated fat-a randomized controlled dietary intervention study.** Am J Clin Nutr.  <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/31051508), [Full text](https://academic.oup.com/ajcn/article/109/5/1239/5480602)

1. `2019` Dhar I, **Lysne V**, Svingen GFT, Ueland PM, Gregory JF, Bønaa KH, Nygård OK. <br> **Elevated plasma cystathionine is associated with increased risk of mortality among patients with suspected or established coronary heart disease.** Am J Clin Nutr. <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/31005968), [Full text](https://academic.oup.com/ajcn/article/109/6/1546/5475746)

1. `2019` Puaschitz NG, Assmus J, Strand E, Karlsson T, Vinknes KJ, **Lysne V**, Drevon CA, Tell GS, Dierkes J, Nygård O. <br> **Adherence to the Healthy Nordic Food Index and the incidence of acute myocardial infarction and mortality among patients with stable angina pectoris.** J Hum Nutr Diet.  <br>[PubMed](https://www.ncbi.nlm.nih.gov/pubmed/30091209), [Full text](https://onlinelibrary.wiley.com/doi/full/10.1111/jhn.12592)

1. `2018` Dhar I, Svingen GFT, Ueland PM, **Lysne V**, Svenningsson MM, Tell GS, Nygård OK. <br> **Plasma Cystathionine and Risk of Incident Stroke in Patients With Suspected Stable Angina Pectoris.** J Am Heart Assoc. <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/30371177), [Full text](https://www.ahajournals.org/doi/full/10.1161/JAHA.118.008824)

1. `2018` Bjørndal B, Bruheim I, Lysne V, Ramsvik MS, Ueland PM, Nordrehaug JE, Nygård OK, Berge RK. <br> **Plasma choline, homocysteine and vitamin status in healthy adults supplemented with krill oil: a pilot study.** Scand J Clin Lab Invest. <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/30261756), [Full text](https://www.tandfonline.com/doi/full/10.1080/00365513.2018.1512716)

1. `2018` Dhar I, Lysne V, Seifert R, Svingen GFT, Ueland PM, Nygård OK. <br> **Plasma methionine and risk of acute myocardial infarction: Effect modification by established risk factors.** Atherosclerosis. <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/29621698)

1. `2018` Strauss P, Marti HP, Beisland C, Scherer A, **Lysne V**, Leh S, Flatberg A, Koch E, Beisvag V, Landolt L, Skogstrand T, Eikrem ØS. <br> **Expanding the Utilization of Formalin-Fixed, Paraffin-Embedded Archives: Feasibility of miR-Seq for Disease Exploration and Biomarker Development from Biopsies with Clear Cell Renal Cell Carcinoma.** Int J Mol Sci. <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/29534467), [Full text](https://www.mdpi.com/1422-0067/19/3/803)

1. `2018` Strand E, Rebnord EW, Flygel MR, **Lysne V**, Svingen GFT, Tell GS, Løland KH, Berge RK, Svardal A, Nygård O, Pedersen ER. <br> **Serum Carnitine Metabolites and Incident Type 2 Diabetes Mellitus in Patients With Suspected Stable Angina Pectoris.** J Clin Endocrinol Metab. <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/29325058), [Full text](https://academic.oup.com/jcem/article/103/3/1033/4794884)

1. `2017` DeRatt BN, Ralat MA, **Lysne V**, Tayyari F, Dhar I, Edison AS, Garrett TJ, Midttun Ø, Ueland PM, Nygård OK, Gregory JF 3rd. <br> **Metabolomic Evaluation of the Consequences of Plasma Cystathionine Elevation in Adults with Stable Angina Pectoris.** J Nutr. <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/28794210), [Full text](https://academic.oup.com/jn/article/147/9/1658/4743549)

1. `2016` Hannibal L, **Lysne V**, Bjørke-Monsen AL, Behringer S, Grünert SC, Spiekerkoetter U, Jacobsen DW, Blom HJ. <br> **Biomarkers and Algorithms for the Diagnosis of Vitamin B12 Deficiency.** Front Mol Biosci. <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/) 

1. `2016` **Lysne V**, Strand E, Svingen GF, Bjørndal B, Pedersen ER, Midttun Ø, Olsen T, Ueland PM, Berge RK, Nygård O. <br> **Peroxisome Proliferator-Activated Receptor Activation is Associated with Altered Plasma One-Carbon Metabolites and B-Vitamin Status in Rats.** Nutrients. <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/26742069), [Full text](https://www.mdpi.com/2072-6643/8/1/26)

1. `2015` **Lysne V**, Bjørndal B, Vik R, Nordrehaug JE, Skorve J, Nygård O, Berge RK. <br> **A Protein Extract from Chicken Reduces Plasma Homocysteine in Rats.** Nutrients. <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/26053618), [Full text](https://www.mdpi.com/2072-6643/7/6/4498)

1. `2015` Øyen J, Svingen GF, Gjesdal CG, Tell GS, Ueland PM, **Lysne V**, Apalset EM, Meyer K, Vollset SE, Nygård OK. <br> **Plasma dimethylglycine, nicotine exposure and risk of low bone mineral density and hip fracture: the Hordaland Health Study.** Osteoporos Int. <br> [PubMed](https://www.ncbi.nlm.nih.gov/pubmed/25616506), [Full text](https://link.springer.com/article/10.1007%2Fs00198-015-3030-4)

[Back to the top of journal publications](#Journal)

## Other publications {#Other}

1. `2019` Myklebust-Hansen T, **Lysne, V** <br> **FENS 2019: Malnutrition in an obese world – European perspective.** Norsk Tidsskrift for Ernæring 2019 (4).

1. `2019` Matre ÅO, **Lysne, V**. <br> **B12-tilskudd uten B12-mangel.** Norsk Tidsskrift for Ernæring 2019 (3). 

1. `2019` **Lysne V**. <br> **12. Internasjonale konferanse om enkarbonmetabolisme.** B-vitaminer og homocystein. Norsk Tidsskrift for Ernæring, 2019 (3).

1. `2018` **Lysne V**, Marienborg I, Olsen T. <br> **FASEB-konferanse om folat, vitamin B12 og enkarbonmetabolisme**. Norsk Tidsskrift for Ernæring, 2018 (3).

1. `2018` **Lysne V**, Olsen T. <br> **Feilkilder i ernæringsepidemiologi.** Norsk Tidsskrift for Ernæring, 2018(2). 

1. `2017` **Lysne V**. <br> **Glimt fra den 11. internasjonale konferansen om homocystein og enkarbonmetabolisme i Århus.** Norsk tidsskrift for Ernæring, 2017(3).

1. `2017` **Lysne V**, Olsen T. <br> **Konfidensintervaller – hva kan de fortelle deg?** Norsk Tidsskrift for Ernæring, 2017(1)

1. `2016` **Lysne V**, Olsen T. <br> **P-verdier. Veiledende eller villedende? En simulert studie.** Norsk Tidsskrift for Ernæring, 2016(4).

1. `2016` Christensen JJ, **Lysne V**. <br> **Støtter lørdagsgodt.** Den Norske Tannlegeforenings Tidende, 2016(5). 

1. `2015` Olsen T, **Lysne V**. <br> **Ta faget tilbake.** Norsk Tidsskrift for Ernæring, 2015(3).

1. `2015` Kverneland M, Christensen JJ, **Lysne V**. <br> **Lavkarbodietter har kommet for å bli, men hører hjemme i klinikken.** Norsk Tidsskrift for Ernæring, 2015(2).