---
title: "Recommended blogs and webpages"
author: vegard
slug: blogs
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
date: 2019-09-04
lastmod: 2020-04-09
featured: no
draft: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
---
These are blogs and web sites I highly recommend.

## Statistics and research methods

#### [Statistical Modeling, Causal Inference, and Social Science](https://statmodeling.stat.columbia.edu/)
The personal blog of statistics professor Andrew Gelman He writes about statistical methods and interpretations, and frequently publish posts commenting on examples from the literature. 

#### [Datamethods](https://discourse.datamethods.org/)
Datamethods is a statistical discussion forum maintained by statistics professor Frank Harrell.

#### [Credibly curious](https://www.njtierney.com/)
The homepage of Nicholas Tierney, who I met at the RStudio::conf2018 where he presented his R-packages for handling missing data. He is one of the guys behind [R-miss-tastic](https://rmisstastic.netlify.com/), a resource website for missing data.

#### [Less Likely](https://lesslikely.com/)
The homepage of Zad Chow, who writes about statistics, medicine and nutrition. 

#### [The logic of science](https://www.thelogicofscience.com)
The logic of science is a blog focusing on critical thinking, scientific methods and logical fallacies. 

#### [Data Imaginist](https://www.data-imaginist.com/)
Data Imaginist is written by Thomas Lin Pedersen, a software engineer at Rstudio. He is one of the main maintenants of ggplot2, and on his blog i mostly writes about stuff related to data visualization. 

#### [Tidyverse blog](https://www.tidyverse.org/blog/)
Stay updated on the different R-packages of the Tidyverse!


## Nutrition
#### [Sunn Skepsis (Norwegian)](https://sunnskepsis.wordpress.com/)
The blog of Erik Arnesen, public health nutritionist and PhD student at the University of Oslo.